name: sleepless_app
description: sleepless app
publish_to: 'none'

version: 0.1.0

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cyclic_dependency_checks:
    git:
      url: https://github.com/dam5s/cyclic_dependency_checks.git
      ref: release/0.1.0

  shared_preferences: any
  cupertino_icons: ^1.0.2
  http: ^1.2.1
  logger: ^2.1.0
  intl: ^0.19.0
  flutter_svg: 2.0.10+1
  animated_segmented_tab_control: ^2.0.0
  just_audio: ^0.9.37
  just_audio_background: ^0.0.1-beta.11
  firebase_core: ^3.5.0
  firebase_analytics: ^11.3.2
  firebase_crashlytics: ^4.1.2
  email_validator: ^3.0.0
  fluttertoast: ^8.2.5

  audio_session: any
  rxdart: any
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  test: ^1.24.9
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    #- assets/audios/
    - assets/icons/
    - assets/images/
    - assets/resources.json

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
     - family: Montserrat
       fonts:
         - asset: assets/fonts/Montserrat-Bold.ttf

  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
